source = $HOME/.config/hypr/mocha.conf

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = JetBrainsMono Nerd Font

# GENERAL
general {
  disable_loading_bar = true
  hide_cursor = true
}

# USER AVATAR
image {
  monitor =
  path = $HOME/.face
  size = 100
  border_color = $accent
  position = 0, 75
  halign = center
  valign = center
}

# BACKGROUND
background {
  monitor =
  path = $HOME/wallpapers/comfy-home.png
  blur_passes = 1
  color = $base
}

# uncomment to enable fingerprint authentication
auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250 # in milliseconds
    }
}

# TIME (external monitors)
label {
  monitor = DP-1, DP-2, DP-3
  text = $TIME
  color = $text
  font_size = 45
  font_family = $font
  position = -30, 0
  halign = right
  valign = top
}

# DATE (external monitors)
label {
  monitor = DP-1, DP-2, DP-3
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 12
  font_family = $font
  position = -30, -75
  halign = right
  valign = top
}

# INPUT FIELD (external monitors)
input-field {
  monitor =
  size = 200, 45
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  font_color = $text
  fade_on_empty = false
  placeholder_text = <span foreground="##$textAlpha"><i> Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -47
  halign = center
  valign = center
}

# TIME eDP-1
label {
  monitor = eDP-1
  text = $TIME
  color = $text
  font_size = 90
  font_family = $font
  position = -30, 0
  halign = right
  valign = top
}

# DATE eDP-1
label {
  monitor = eDP-1
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 25
  font_family = $font
  position = -30, -150
  halign = right
  valign = top
}

# INPUT FIELD eDP-1
input-field {
  monitor = eDP-1
  size = 450, 90
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  font_color = $text
  fade_on_empty = false
  placeholder_text = <span foreground="##$textAlpha"><i>  Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -47
  halign = center
  valign = center
}
