[
    [
        "mainmenu",
        "movies",
        "icon",
        "DefaultMovies.png"
    ],
    [
        "mainmenu",
        "24001",
        "translatedPath",
        "ActivateWindow(AddonBrowser)"
    ],
    [
        "mainmenu",
        "24001",
        "icon",
        "DefaultAddon.png"
    ],
    [
        "mainmenu",
        "20434",
        "icon",
        "DefaultSets.png"
    ],
    [
        "mainmenu",
        "tvshows",
        "icon",
        "DefaultTVShows.png"
    ],
    [
        "mainmenu",
        "133",
        "icon",
        "DefaultMusicArtists.png"
    ],
    [
        "mainmenu",
        "132",
        "icon",
        "DefaultMusicAlbums.png"
    ],
    [
        "mainmenu",
        "1036",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "settings",
        "icon",
        "DefaultShortcut.png"
    ]
]