set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ",xterm*:Tc"
set -s escape-time 0

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g base-index 1
set -g detach-on-destroy off
set -g history-limit 1000000
set -g renumber-windows on
set -g status-position top
setw -g mode-keys vi

# Pane navigation
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Alt shortcuts (only on non-framework hosts, so they pass through over SSH)
if-shell '[ "$(hostname)" != "framework" ]' 'bind -n M-q new-window'
if-shell '[ "$(hostname)" != "framework" ]' 'bind -n M-c kill-window'
if-shell '[ "$(hostname)" != "framework" ]' 'bind -n M-n next-window'
if-shell '[ "$(hostname)" != "framework" ]' "bind -n M-o run-shell '~/.tmux/plugins/tmux-sessionx/scripts/sessionx.sh'"

# Fuzzy file search
bind-key f run "tmux split-window -p 30 'fzf --preview \"cat {}\" --bind \"ctrl-y:execute(echo -n {} | pbcopy)\"'"
bind-key S setw synchronize-panes
set-hook -g after-new-window 'setw synchronize-panes on'


# Copy mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'

# Open TODO.md
bind -r D neww -c "#{pane_current_path}" "[[ -e TODO.md ]] && nvim TODO.md || nvim ~/personal/dev/todo.md"

# Find window replacement
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'catppuccin/tmux#v2.1.1'
set -g @plugin 'omerxx/tmux-sessionx'

# Sessionx
set -g @sessionx-bind 'o'
set -g @sessionx-x-path '~/dotfiles'
set -g @sessionx-window-height '85%'
set -g @sessionx-window-width '75%'
set -g @sessionx-fzf-builtin-tmux 'on'
set -g @sessionx-zoxide-mode 'on'

# Catppuccin
set-option -g @catppuccin_window_default_text " #W"
set-option -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_status_background "#1e1e2e"
set -ogq @catppuccin_pane_left_separator ""
set -ogq @catppuccin_pane_right_separator " "
set -ogq @catppuccin_pane_middle_separator " █"
set -ogq @catppuccin_pane_default_text "##{b:pane_current_path}"
set -ogq @catppuccin_status_connect_separator "no"
set -ogq @catppuccin_status_right_separator " "

# Status line
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right ""
set-option -ag status-right "#{pomodoro_status}  "
set-option -ag status-right "#{E:@catppuccin_status_application}"
set-option -ag status-right "#{E:@catppuccin_status_session}"

run '~/.tmux/plugins/tpm/tpm'


